name: Deploy to GitHub Pages

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Run tests
        run: npm test  # Execute unit tests

      - name: Deploy to GitHub Pages (if tests pass)
        uses: actions/deploy-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: $DEFAULT_BRANCH  # Deploy to the default branch
        if: success()  # Only deploy if tests pass

  test-and-build:  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint  # Execute linting checks

      - name: Run tests
        run: npm test
